Update ocsm

diff --git a/files/bin/ocsm b/files/bin/ocsm
--- a/files/bin/ocsm
+++ b/files/bin/ocsm
@@ -26,47 +26,45 @@ N='\033[1;37m' # Putih
 #--------------------------------------------------------
 COREDIR="/etc/openclash/core"
 
-#	Core Names
+# Core Names
 CORE="$COREDIR/clash"
 TUN="$COREDIR/clash_tun"
 GAME="$COREDIR/clash_game"
 
-#	Vernesong Core Names
+# Vernesong Core Names
 VSCORE="$COREDIR/clash_vernesong"
 VSTUN="$COREDIR/clash_tun_vernesong"
 VSGAME="$COREDIR/clash_game_vernesong"
 
-#	Dreamacro Core Names
+# Dreamacro Core Names
 DMCORE="$COREDIR/clash_dreamacro"
-DMTUNPREM="$COREDIR/clash_tun_dreamacro"
+DMTUN="$COREDIR/clash_tun_dreamacro"
 
-#	Meta Core Name
-META="$COREDIR/clash_tun_meta"
+# Meta Core Name
+META="$COREDIR/clash_meta"
 
-#	Core Extensions
+# Core Extensions
 TARGZ=".tar.gz"
 DOTGZ=".gz"
 
-#	Core Extensions
+# Core Extensions
 ROOTCORE="/root/clash"
 
 ARCH=$(grep core_version /etc/config/openclash | awk -F"'" '$0=$2')
 #ORILINK=$(curl -sL http://api.github.com/repos/Dreamacro/clash/releases/tags/premium | grep /clash-linux-$1 | sed 's/.*url\": \"//g' | sed 's/\"//g')
 #PREMLINK=$(curl -sL http://api.github.com/repos/vernesong/OpenClash/releases/tags/Clash | grep /clash-linux-$1 | sed 's/.*url\": \"//g' | sed 's/\"//g')
-MAINCORE=$(if [[ -f $CORE ]] && [[ -f $PREM ]]; then echo -e "${G}Original${N}"; elif [[ -f $CORE ]] && [[ -f $ORI ]]; then echo -e "${Y}Premium${N}"; else [[ ! -f $ORI ]] && [[ ! -f $PREM ]] && [[ ! -f $CORE ]]; echo -e "${R}Unknown${N}"; fi)
-TUNCORE=$(if [[ -f $CORE ]] && [[ -f $PREM ]]; then echo -e "${G}Original${N}"; elif [[ -f $CORE ]] && [[ -f $ORI ]]; then echo -e "${Y}Premium${N}"; else [[ ! -f $ORI ]] && [[ ! -f $PREM ]] && [[ ! -f $CORE ]]; echo -e "${R}Unknown${N}"; fi)
-GAMECORE=$(if [[ -f $CORE ]] && [[ -f $PREM ]]; then echo -e "${G}Original${N}"; elif [[ -f $CORE ]] && [[ -f $ORI ]]; then echo -e "${Y}Premium${N}"; else [[ ! -f $ORI ]] && [[ ! -f $PREM ]] && [[ ! -f $CORE ]]; echo -e "${R}Unknown${N}"; fi)
+DMCORESTAT=$(if [[ -f $VSCORE ]] && [[ -f $VSTUN ]]; then echo -e "${G}Installed (Used)${N}"; elif [[ -f $DMCORE ]] && [[ -f $DMTUN ]]; then echo -e "${Y}Installed${N}"; else echo -e "${R}Unavailable${N}"; fi)
+VSCORESTAT=$(if [[ -f $DMCORE ]] && [[ -f $DMTUN ]]; then echo -e "${G}Installed (Used)${N}"; elif [[ -f $VSCORE ]] && [[ -f $VSTUN ]]; then echo -e "${Y}Installed${N}"; else echo -e "${R}Unavailable${N}"; fi)
+METACORESTAT=$(if [[ -f $META ]]; then echo -e "${G}Installed${N}"; else echo -e "${R}Unavailable${N}"; fi)
 IPKVER=$(opkg list-installed | grep luci-app-openclash | sed -e 's/luci-app-openclash - //g' )
-IPKSTAT=$(if [[ $IPKVER == *"."* ]]; then echo -e "${G}Installed${N}";else echo -e "${R}Not Available${N}"; fi)
+IPKSTAT=$(if [[ $IPKVER == *"."* ]]; then echo -e "${G}Installed${N}";else echo -e "${R}Unavailable${N}"; fi)
 #wget $(curl -sL https://github.com/vernesong/OpenClash/releases | grep luci-app-openclash_ | sed -e 's/\"//g' -e 's/ //g' -e 's/rel=.*//g' -e 's#<ahref=#http://github.com#g' | awk 'FNR <= 1')
-SCRIPTVER="2.8"
-
-ls /root | grep -q shrek && echo "Ada filenya"
+SCRIPTVER="2.9"
 
 #--------------------------------------------------------
 #   If you use some codes frome here, please give credit to www.helmiau.com
 #--------------------------------------------------------
-function helmi_clash_permissions() {
+function helmi_clash_chmod() {
 	echo -e "${Y}"
 	chmod +x $CORE*
 	echo -e "${G}"
@@ -99,35 +97,48 @@ function helmi_clash_stop() {
 #--------------------------------------------------------
 function helmi_download_dreamacro() {
 	echo -e "${Y}Downloading Dreamacro clash core..."
-	wget -O $ROOTCORE-$ARCH$DOTGZ $(curl -sL http://api.github.com/repos/Dreamacro/clash/releases | grep premium/clash-$ARCH | awk -F '"' '{print $4}' | sed 's/https/http/g')
+	wget -O $ROOTCORE-dm-$ARCH$DOTGZ $(curl -sL http://api.github.com/repos/Dreamacro/clash/releases | grep premium/clash-$ARCH | awk -F '"' '{print $4}' | sed 's/https/http/g')
 	echo -e "${G}Dreamacro clash core downloaded..."
 	sleep 2
 	echo -e "${Y}Downloading Dreamacro clash TUN Premium core..."
-	wget -O $ROOTCORE-tun-$ARCH$DOTGZ $(curl -sL http://api.github.com/repos/Dreamacro/clash/releases/tags/premium | grep premium/clash-$ARCH | awk -F '"' '{print $4}' | sed 's/https/http/g')
+	wget -O $ROOTCORE-dmtun-$ARCH$DOTGZ $(curl -sL http://api.github.com/repos/Dreamacro/clash/releases/tags/premium | grep premium/clash-$ARCH | awk -F '"' '{print $4}' | sed 's/https/http/g')
 	echo -e "${G}Dreamacro clash TUN Premium core downloaded..."
 }
 
-function helmi_install_premium() {
-	if [[ -s $ROOTCORE-$ARCH$DOTGZ ]]; then
+function helmi_install_dreamacro() {
+	# Install Dreamacro Main Core
+	if [[ -s $ROOTCORE-dm-$ARCH$DOTGZ ]]; then
 		echo -e "${G}"
-		gunzip -d $ROOTCORE-$ARCH$DOTGZ
-		if [[ $CURRENTCORE = "Original" ]]; then
-			mv $ROOTCORE-$ARCH $PREM
-		else
-			mv $ROOTCORE-$ARCH $CORE
-		fi
-		echo "  Premium Core Install Done...."
+		gunzip -d $ROOTCORE-dm-$ARCH$DOTGZ
+		mv $ROOTCORE-dm-$ARCH $DMCORE
+		echo "  Dreamacro Main Core Install Done...."
 	else
 		echo -e "${R}"
-		echo "  Premium Core Install Failed...."
+		echo "  Dreamacro Main Core Install Failed...."
+		echo -e "${G}"
+	fi
+	# Install Dreamacro TUN Core
+	if [[ -s $ROOTCORE-dmtun-$ARCH$DOTGZ ]]; then
+		echo -e "${G}"
+		gunzip -d $ROOTCORE-dmtun-$ARCH$DOTGZ
+		mv $ROOTCORE-dmtun-$ARCH $DMTUN
+		echo "  Dreamacro TUN Core Install Done...."
+	else
+		echo -e "${R}"
+		echo "  Dreamacro TUN Core Install Failed...."
 		echo -e "${G}"
 	fi
 }
 
 function helmi_switch_dreamacro() {
 	echo -e "${Y}"
-	mv $CORE $ORI
-	mv $PREM $CORE
+	# Move Main Core
+	[[ ! -f $VSCORE ]] && [[ -f $DMCORE ]] && mv $CORE $VSCORE && mv $DMCORE $CORE
+	echo "  Dreamacro Main Core Switched....!"
+	# Move TUN Core
+	[[ ! -f $VSTUN ]] && [[ -f $DMTUN ]] && [[ -f $META ]] && mv $TUN $VSTUN && mv $DMTUN $TUN
+	[[ -f $VSTUN ]] && [[ -f $DMTUN ]] && [[ ! -f $META ]] && mv $TUN $META && mv $DMTUN $TUN
+	echo "  Dreamacro TUN Core Switched....!"
 	echo -e "${G}"
 }
 
@@ -136,31 +147,29 @@ function helmi_switch_dreamacro() {
 #--------------------------------------------------------
 function helmi_download_meta() {
 	echo -e "${Y}Downloading Meta TUN Premium core..."
-	wget -O $ROOTCORE-$ARCH$DOTGZ $(curl -sL http://api.github.com/repos/MetaCubeX/Clash.Meta/releases | grep /Clash.Meta-$1 | awk -F '"' '{print $4}' | sed -n '1p' | sed 's/https/http/g')
+	wget -O $ROOTCORE-meta-$ARCH$DOTGZ $(curl -sL http://api.github.com/repos/MetaCubeX/Clash.Meta/releases | grep /Clash.Meta-$1 | awk -F '"' '{print $4}' | sed -n '1p' | sed 's/https/http/g')
 	echo -e "${G}Meta TUN Premium core downloaded..."
 }
 
-function helmi_install_meta() {
-	if [[ -s $ROOTCORE-$ARCH$DOTGZ ]]; then
+function helmi_install_meta() {	
+	if [[ -s $ROOTCORE-meta-$ARCH$DOTGZ ]]; then
 		echo -e "${G}"
-		gunzip -d $ROOTCORE-$ARCH$DOTGZ
-		if [[ $CURRENTCORE = "Original" ]]; then
-			mv $ROOTCORE-$ARCH $PREM
-		else
-			mv $ROOTCORE-$ARCH $CORE
-		fi
-		echo "  Premium Core Install Done...."
+		gunzip -d $ROOTCORE-meta-$ARCH$DOTGZ
+		mv $ROOTCORE-meta-$ARCH $META
+		echo "  Meta Core Install Done...."
 	else
 		echo -e "${R}"
-		echo "  Premium Core Install Failed...."
+		echo "  Meta Core Install Failed...."
 		echo -e "${G}"
 	fi
 }
 
 function helmi_switch_meta() {
 	echo -e "${Y}"
-	mv $CORE $ORI
-	mv $PREM $CORE
+	# Move TUN Core
+	[[ ! -f $VSTUN ]] && [[ -f $DMTUN ]] && [[ -f $META ]] && mv $TUN $VSTUN && mv $META $TUN
+	[[ -f $VSTUN ]] && [[ ! -f $DMTUN ]] && [[ -f $META ]] && mv $TUN $DMTUN && mv $META $TUN
+	echo "  Meta TUN Core Switched....!"
 	echo -e "${G}"
 }
 
@@ -169,38 +178,65 @@ function helmi_switch_meta() {
 #--------------------------------------------------------
 function helmi_download_vernesong() {
 	echo -e "${Y}Downloading Vernesong clash core..."
-	wget -O $ROOTCORE-$ARCH$TARGZ $(curl -sL http://api.github.com/repos/vernesong/OpenClash/releases/tags/Clash | grep Clash/clash-$ARCH | awk -F '"' '{print $4}' | sed 's/https/http/g')
+	wget -O $ROOTCORE-vs-$ARCH$TARGZ $(curl -sL http://api.github.com/repos/vernesong/OpenClash/releases/tags/Clash | grep Clash/clash-$ARCH | awk -F '"' '{print $4}' | sed 's/https/http/g')
 	echo -e "${G}Vernesong clash core downloaded..."
 	sleep 2
 	echo -e "${Y}Downloading Vernesong clash TUN Premium core"
-	wget -O $ROOTCORE-tun-$ARCH$DOTGZ $(curl -sL http://api.github.com/repos/vernesong/OpenClash/releases/tags/TUN-Premium | grep TUN-Premium/clash-$ARCH | awk -F '"' '{print $4}' | sed 's/https/http/g')
+	wget -O $ROOTCORE-vstun-$ARCH$DOTGZ $(curl -sL http://api.github.com/repos/vernesong/OpenClash/releases/tags/TUN-Premium | grep TUN-Premium/clash-$ARCH | awk -F '"' '{print $4}' | sed 's/https/http/g')
 	echo -e "${G}Vernesong clash TUN Premium core downloaded..."
 	sleep 2
 	echo -e "${Y}Downloading Vernesong clash TUN Game core"
-	wget -O $ROOTCORE-game-$ARCH$TARGZ $(curl -sL http://api.github.com/repos/vernesong/OpenClash/releases/tags/TUN | grep TUN/clash-$ARCH | awk -F '"' '{print $4}' | sed 's/https/http/g')
+	wget -O $ROOTCORE-vsgame-$ARCH$TARGZ $(curl -sL http://api.github.com/repos/vernesong/OpenClash/releases/tags/TUN | grep TUN/clash-$ARCH | awk -F '"' '{print $4}' | sed 's/https/http/g')
 	echo -e "${G}Vernesong clash TUN Game core downloaded..."
 }
 
 function helmi_install_vernesong() {
-	if [[ -s $ROOTCORE-$ARCH$TARGZ ]]; then
-		tar xzf $ROOTCORE-$ARCH$TARGZ -C /root/
-		if [[ $CURRENTCORE = "Premium" ]]; then
-			mv $ROOTCORE $ORI
-			rm -f $ROOTCORE-$ARCH$TARGZ || true
-		else
-			mv $ROOTCORE $CORE
-			rm -f $ROOTCORE-$ARCH$TARGZ || true
-		fi
-		echo -e "${G}Install Done....${G}"
+	# Install Vernesong Main Core
+	if [[ -s $ROOTCORE-vs-$ARCH$TARGZ ]]; then
+		echo -e "${G}"
+		tar xzf $ROOTCORE-vs-$ARCH$TARGZ -C /root/
+		mv $ROOTCORE $VSCORE
+		rm -f $ROOTCORE-vs-$ARCH$TARGZ || true
+		echo "  Vernesong Main Core Install Done...."
 	else
-		echo -e "${R}Install Failed....${G}"
+		echo -e "${R}"
+		echo "  Vernesong Main Core Install Failed...."
+		echo -e "${G}"
+	fi
+	# Install Vernesong TUN Core
+	if [[ -s $ROOTCORE-vstun-$ARCH$DOTGZ ]]; then
+		echo -e "${G}"
+		gunzip -d $ROOTCORE-vstun-$ARCH$DOTGZ
+		mv $ROOTCORE-vstun-$ARCH $VSTUN
+		echo "  Vernesong TUN Core Install Done...."
+	else
+		echo -e "${R}"
+		echo "  Vernesong TUN Core Install Failed...."
+		echo -e "${G}"
+	fi
+	# Install Vernesong Game Core
+	if [[ -s $ROOTCORE-vsgame-$ARCH$TARGZ ]]; then
+		echo -e "${G}"
+		tar xzf $ROOTCORE-vsgame-$ARCH$TARGZ -C /root/
+		mv $ROOTCORE $VSGAME
+		rm -f $ROOTCORE-vsgame-$ARCH$TARGZ || true
+		echo "  Vernesong TUN Game Core Install Done...."
+	else
+		echo -e "${R}"
+		echo "  Vernesong TUN Game Core Install Failed...."
+		echo -e "${G}"
 	fi
 }
 
 function helmi_switch_vernesong() {
 	echo -e "${Y}"
-	mv $CORE $PREM
-	mv $ORI $CORE
+	# Move Main Core
+	[[ -f $VSCORE ]] && [[ ! -f $DMCORE ]] && mv $CORE $DMCORE && mv $VSCORE $CORE
+	echo "  Dreamacro Main Core Switched....!"
+	# Move TUN Core
+	[[ -f $VSTUN ]] && [[ ! -f $DMTUN ]] && [[ -f $META ]] && mv $TUN $DMTUN && mv $VSTUN $TUN
+	[[ -f $VSTUN ]] && [[ -f $DMTUN ]] && [[ ! -f $META ]] && mv $TUN $META && mv $VSTUN $TUN
+	echo "  Dreamacro TUN Core Switched....!"
 	echo -e "${G}"
 }
 
@@ -317,37 +353,33 @@ EOF
 #   If you use some codes frome here, please give credit to www.helmiau.com
 #--------------------------------------------------------
 echo -e "${N}=====================================${G}"
-echo "    OpenClash Script Manager v$SCRIPTVER"
-echo "         Created by helmiau"
+echo -e "    OpenClash Script Manager ${R}v$SCRIPTVER${G}"
+echo -e "         Created by ${Y}helmiau"
 echo -e "${N}=====================================${N}"
-echo -e "  ${Y}Architecture  : $ARCH"
-echo -e "  ${Y}OpenClash App : $IPKSTAT"
-echo -e "  ${Y}App Version   : $IPKVER"
+echo -e "  ${Y}Architecture   : $ARCH"
+echo -e "  ${Y}OpenClash App  : $IPKSTAT"
+echo -e "  ${Y}App Version    : $IPKVER"
+echo -e "  ${Y}Dreamacro Core : $DMCORESTAT"
+echo -e "  ${Y}Vernesong Core : $VSCORESTAT"
+echo -e "  ${Y}Meta Core      : $METACORESTAT"
 echo -e "${N}=====================================${G}"
-echo -e "  ${Y}Main Core     : $MAINCORE"
-echo -e "  ${Y}TUN Core      : $TUNCORE"
-echo -e "  ${Y}Game Core     : $GAMECORE"
-echo -e "${N}=====================================${G}"
-if [[ $MAINCORE = "Original" ]]; then
-	echo "  Switch to Premium core    : s"
-elif [[ $MAINCORE = "Premium" ]]; then
-	echo "  Switch to Origin core     : s"
+if [[ $VSCORESTAT == *"(Used)"* ]]; then
+	echo "  Switch to Dreamacro core  : s"
 else
-	echo "  Install all cores         : s"
+	echo "  Switch to Vernesong core  : s"
 fi
 echo -e "${N}=====================================${G}"
-echo "  Install Dreamacro core    : p"
-echo "  Install Vernesong core    : o"
+echo "  Install Dreamacro core    : d"
+echo "  Install Vernesong core    : v"
 echo "  Install Meta core         : m"
-echo -e "${N}=====================================${G}"
 echo "  Re-Install all cores      : r"
 echo -e "${N}=====================================${Y}"
 echo "  Install OpenClash Stable  : is"
 echo "  Install OpenClash Dev     : id"
-echo -e "${N}=====================================${N}"
-echo "  Start OpenClash           : c"
-echo "  Stop OpenClash            : h"
-echo -e "${N}=====================================${N}"
+echo -e "${N}=====================================${R}"
+echo "  Start OpenClash           : st"
+echo "  Stop OpenClash            : sp"
+echo -e "${N}=====================================${Y}"
 echo "  Add Adblock Rules         : b"
 echo "  Update OCSM Script        : u"
 echo -e "${N}=====================================${G}"
@@ -358,56 +390,66 @@ read -r OPT
 #   If you use some codes frome here, please give credit to www.helmiau.com
 #--------------------------------------------------------
 if [[ $OPT = "s" ]];then
-	helmi_clash_stop \ &&
-	if [[ -f $CORE ]] && [[ -f $PREM ]];then
-		echo "  Switching to Premium Core...."
-		helmi_switch_premium
-	elif [[ -f $CORE ]] && [[ -f $ORI ]];then
-		echo "  Switching to Original Core...."
-		helmi_switch_original
-	elif [[ -f $CORE ]] && [[ ! -f $PREM ]];then
-		echo "  Downloading Premium Core...."
-		helmi_install_premium
-	elif [[ -f $CORE ]] && [[ ! -f $ORI ]];then
-		echo "  Downloading Original Core...."
-		helmi_install_original
-	elif [[ ! -f $ORI ]] && [[ ! -f $PREM ]] && [[ ! -f $CORE ]];then
-		echo "  Downloading Premium Core...."
-		helmi_install_premium
-		echo "  Downloading Original Core...."
-		helmi_install_original
+	helmi_clash_stop
+	if [[ $VSCORESTAT == *"(Used)"* ]]; then
+		echo "  Switching to Dreamacro core..."
+		if [[ -f $DMCORE ]] && [[ -f $DMTUN ]];then
+			helmi_switch_dreamacro
+			echo -e "${G}  Switch to Dreamacro core Done...!${N}"
+		else
+			echo -e "${R}  Switch to Dreamacro core Error...!${N}"
+			echo -e "${R}  Reinstall Dreamacro core please..!${N}"
+		fi
+	else
+		echo "  Switching to Vernesong core..."
+		if [[ -f $VSCORE ]] && [[ -f $VSTUN ]];then
+			helmi_switch_vernesong
+			echo -e "${G}  Switch to Vernesong core Done...!${N}"
+		else
+			echo -e "${R}  Switch to Vernesong core Error...!${N}"
+			echo -e "${R}  Reinstall Vernesong core please..!${N}"
+		fi
 	fi
-elif [[ $OPT = "p" ]];then
-	echo "  Downloading Premium Core...."
-	helmi_download_premium
+elif [[ $OPT = "d" ]];then # Download & Install Dreamacro Core
+	echo "  Downloading Dreamacro Core...."
+	helmi_download_dreamacro
 	echo "  Stopping OpenClash...."
 	helmi_clash_stop
-	echo "  Installing Premium Core...."
-	helmi_install_premium
-elif [[ $OPT = "o" ]];then
-	echo "  Downloading Original Core...."
-	helmi_download_original
+	echo "  Installing Dreamacro Core...."
+	helmi_install_dreamacro
+elif [[ $OPT = "v" ]];then # Download & Install Vernesong Core
+	echo "  Downloading Vernesong Core...."
+	helmi_download_vernesong
 	echo "  Stopping OpenClash...."
 	helmi_clash_stop
-	echo "  Installing Original Core...."
-	helmi_install_original
-elif [[ $OPT = "t" ]];then
-	echo "  Downloading TUN Core...."
-	helmi_download_tun
+	echo "  Installing Vernesong Core...."
+	helmi_install_vernesong
+elif [[ $OPT = "m" ]];then # Download & Install Meta Core
+	echo "  Downloading Meta Core...."
+	helmi_download_meta
 	echo "  Stopping OpenClash...."
 	helmi_clash_stop
-	echo "  Installing TUN Core...."
-	helmi_install_tun
-elif [[ $OPT = "g" ]];then
-	echo "  Downloading Game Core...."
-	helmi_download_game
+	echo "  Installing Meta Core...."
+	helmi_install_meta
+elif [[ $OPT = "r" ]];then # Reinstall All Cores
+	echo "  Downloading Dreamacro Core...."
+	helmi_download_dreamacro
+	echo "  Downloading Vernesong Core...."
+	helmi_download_vernesong
+	echo "  Downloading Meta Core...."
+	helmi_download_meta
 	echo "  Stopping OpenClash...."
 	helmi_clash_stop
-	echo "  Installing Game Core...."
-	helmi_install_game
-elif [[ $OPT = "h" ]];then  #Stop OpenClash
-	echo "  Stopping OpenClash...."
-	helmi_clash_stop
+	echo "  Installing Dreamacro Core...."
+	helmi_install_dreamacro
+	echo "  Installing Vernesong Core...."
+	helmi_install_vernesong
+	echo "  Installing Meta Core...."
+	helmi_install_meta
+	echo "  Configuring permissions...."
+	helmi_clash_chmod
+	echo "  Starting Clash...."
+	helmi_clash_start
 elif [[ $OPT = "is" ]];then # Install IPK Stable
 	echo "  Downloading OpenClash App - Stable Release...."
 	helmi_download_ipk
@@ -415,55 +457,25 @@ elif [[ $OPT = "is" ]];then # Install IPK Stable
 	helmi_clash_stop
 	echo "  Installing OpenClash App...."
 	helmi_install_ipk
-elif [[ $OPT = "id" ]];then # Install IPK Beta
+elif [[ $OPT = "id" ]];then # Install IPK Developer
 	echo "  Downloading OpenClash App - Developer Release...."
 	helmi_download_ipk_dev
 	echo "  Stopping OpenClash...."
 	helmi_clash_stop
 	echo "  Installing OpenClash App...."
 	helmi_install_ipk
+elif [[ $OPT = "st" ]];then # Start OpenClash
+	echo "  Configuring permissions...."
+	helmi_clash_chmod
+	echo "  Starting Clash...."
+	helmi_clash_start
+	echo "  Done...."
+elif [[ $OPT = "sp" ]];then # Stop OpenClash
+	echo "  Stopping OpenClash...."
+	helmi_clash_stop
 elif [[ $OPT = "b" ]];then # Install Adblock
 	echo "  Installing Adblock Rules...."
 	helmi_adblock
-elif [[ $OPT = "r" ]];then # Reinstall Core
-	echo "  Downloading Premium Core...."
-	helmi_download_premium
-	echo "  Stopping OpenClash...."
-	helmi_clash_stop
-	echo "  Installing Premium Core...."
-	helmi_install_premium
-	echo "  Downloading Original Core...."
-	helmi_download_original
-	echo "  Installing Original Core...."
-	helmi_install_original
-	echo "  Downloading TUN Core...."
-	helmi_download_tun
-	echo "  Installing TUN Core...."
-	helmi_install_tun
-	echo "  Downloading Game Core...."
-	helmi_download_game
-	echo "  Installing Game Core...."
-	helmi_install_game
-elif [[ $OPT = "c" ]];then
-	echo "  Configuring permissions...."
-	helmi_clash_cemod
-	echo "  Starting Clash...."
-	helmi_clash_start
-	echo "  Done...."
-	exit
 else
-	echo "  Configuring permissions...."
-	helmi_clash_cemod
-	echo "  Starting Clash...."
-	helmi_clash_start
-	echo "  Done...."
-	echo "  Exiting...."
 	exit
 fi
-echo "====================================="
-
-echo "  Configuring permissions...."
-helmi_clash_cemod
-echo "  Starting Clash...."
-helmi_clash_start
-echo "====================================="
